import type { Metadata } from "next";
import { Bangers } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/provider";
import LoadingIndicator from "@/components/Loading";

const bangers = Bangers({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "QDogeCasino",
  description: "Generated by QDoge Community",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={`${bangers.className} max-w-[1920px] bg-white mx-auto`}>
        <Providers>
          <LoadingIndicator />
          {children}
        </Providers>
      </body>
    </html>
  );
}
